services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
       - MYSQL_ROOT_PASSWORD=jelszo123
       - MYSQL_DATABASE=NestDb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: